### ISSUE TITLE
mac上无法制作mobi电子书，terminal提示如下错误

### ISSUE THREAD

**Issue by tangsengqimadongnagedong** [wax8280/web2kindle#1]
sh: ./web2kindle/bin/kindlegen_mac: Permission denied

**Comment by wax8280** [comment]
权限问题。终端用管理员身份输入：chmod 755 kindlegen_mac路径，即可。

**Comment by tangsengqimadongnagedong** [comment]
修改权限后，制作mobi电子书时，出现错误：
Info:I9018:option: -donotaddsource: Source files will not be added
Error(kindlegen):E30005: Could not find file  C:Usersvincent8280Web2kinlde_data/191640375/知乎收藏夹_20101010_0.opf

**Comment by wax8280** [comment]
你把配置文件的SAVE_PATH项改成你想要的目录啊。

**Comment by tangsengqimadongnagedong** [comment]
多谢，果然是神器，支持
